### ISSUE TITLE
Total Costs Not Correct

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#147]
I have the travel cost on total turned off and it looks to be subtracting it from the package total.
![negative-no-package](https://cloud.githubusercontent.com/assets/19335843/18357268/4ce2ec4a-75be-11e6-92ea-2f20db009115.PNG)
![incorect-price](https://cloud.githubusercontent.com/assets/19335843/18357269/4ce51254-75be-11e6-8ff4-4cd06708311f.PNG)
I have also had this issue with some addons when they are deleted.

**Comment by mikeyhoward1977** [comment]
Hi @peter8rossi,

The behaviour I see on your website would suggest that travel was enabled, events updated (with travel costs), travel disabled.

Together with the issue you have with packages and addons this would result in the behaviour you are seeing - i.e. negative event cost when you adjust the package, addon, employee, event type or venue and is because the travel cost you had associated is being removed.

I have no reports of any issues with the travel feature from any other users. Does this seem like a feasible assumption?

**Comment by peter8rossi** [comment]
No I am fairly sure that this was after I had turned off the travel costs, but it is possible. I have looked at the comment history and see that the cost is showing in the comments, but do not see or know where the flag is to use that cost in the total. However, looking at the history reminds me that I did change the town address (from Baltimore to Middle River) and updated the event. Could that have an impact?

**Comment by mikeyhoward1977** [comment]
Yes, per our exchange just after releasing 1.4, any update to the venue would add travel costs when the event was saved (if auto adding travel costs to event was enabled). This setting was disabled by default following the update to 1.4
