### ISSUE TITLE
Creating an event on 1.4.2 checks the deposit paid and balance paid boxes

### ISSUE THREAD

**Issue by nikmartin** [mdjmplugin/mobile-dj-manager#150]
This happens inconsistently, so it may be driven by some other fields on the form. In one case, i didn't set an event price at all, and it checked both boxes upon save, but allowed me to un-check them. In another case, I did put a price, but zeroed out the deposit field, and when I saved, it marked the deposit as paid, and will not allow me to un-check it. Each time i do and update it's still checked.

**Comment by mikeyhoward1977** [comment]
If no price is inserted then it will set as paid... a zero amount due is considered as paid.

If you add a deposit amount and then un-check paid, does it update correctly?

**Comment by nikmartin** [comment]
Yes, if I go back and add an amount, it lets me uncheck paid and saves properly. On the other event I accidentally checked depoit paid, and no matter what I do I cannot uncheck it. Zeroing out the deposit amount or un-checking the box don't persist when updating the event..

**Comment by mikeyhoward1977** [comment]
On the event you checked deposit paid note the event number and then go to MDJM -> Transactions and delete the deposit transaction.

When you check deposit paid, we create an associated transaction. Subsequent loads of the event page will check for all event transactions and if the total amount of transactions received for the event exceeds the deposit amount, the checkbox is checked automatically.

I'll close this ticket as I do not believe that there is an issue, however if you find otherwise, comment again and I can reopen if necessary
