### ISSUE TITLE
Contract template edit mode does not work

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#165]
Hello,

i have a problem with edit mode in contract template.

If I wan to edit in html mode, i have text in white color. WP editor does not work.
Thank you
Petr

![contract-template-edit-error](https://cloud.githubusercontent.com/assets/19391308/19530628/ecd78e18-9634-11e6-815a-eb6148f6127b.jpg)

**Comment by mikeyhoward1977** [comment]
Hi @petrknap1 - sorry for the delay.

Do you still have this issue? If so, could you provide me with access to your site as an Admin? I do not see this issue elsewhere so need to do some investgigation

**Comment by petrknap1** [comment]
Hi @mikeyhoward1977 , yes, I have it.
You have Admin acces from past.
Thank you.

**Comment by mikeyhoward1977** [comment]
@petrknap1 

Your TinyMCE is also missing on tis page which leads me to believe that there is a JS conflict with another plugin.

In order to investigate I need the Debug plugin installed - https://wordpress.org/plugins/debug/ and enabled. All options except the email option need to be enabled...

![image](https://cloud.githubusercontent.com/assets/11500622/19964724/5ba8c6b8-a1bb-11e6-9b97-828d50076e57.png)

Once you have done, let me know. I am happy to install and configure if you would like me to do so

**Comment by petrknap1** [comment]
@mikeyhoward1977 Hi Mike, sorry for my late answer.
Debug plugin installed.

**Comment by petrknap1** [comment]
@mikeyhoward1977 Solved, problem was in db memory.
