### ISSUE TITLE
Playlist Notifications

### ISSUE THREAD

**Issue by mikeyhoward1977** [mdjmplugin/mobile-dj-manager#178]
Send out an email notification to the client when their playlist has new entries added by a guest

**Comment by rikkilake** [comment]
Likewise can we have a notification as well?  Ideally ONY when the client adds a song for the very first time.  Right now, we have to self-monitor.

**Comment by mikeyhoward1977** [comment]
@rikkilake I'm not sure how useful an employee notification would be only the first time an entry is added.

Say the event is a wedding booked 12 months out and the bride/groom start adding songs to the playlist as soon as the event is confirmed. Employee would likely have no recollection of receiving the email by the time the event comes around.

More useful to have a task that auto sends the playlist to the employee once the playlist closes

**Comment by rikkilake** [comment]
Ah, sounds even better.
Richard


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Mike Howard <notifications@github.com> Date: 07/07/2017  12:02  (GMT+00:00) To: mdjm/mobile-dj-manager <mobile-dj-manager@noreply.github.com> Cc: rikkilake <rikki.lake@ntlworld.com>, Mention <mention@noreply.github.com> Subject: Re: [mdjm/mobile-dj-manager] Playlist Notifications (#178) 
@rikkilake I'm not sure how useful an employee notification would be only the first time an entry is added.
Say the event is a wedding booked 12 months out and the bride/groom start adding songs to the playlist as soon as the event is confirmed. Employee would likely have no recollection of receiving the email by the time the event comes around.
More useful to have a task that auto sends the playlist to the employee once the playlist closes

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mdjm/mobile-dj-manager","title":"mdjm/mobile-dj-manager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mdjm/mobile-dj-manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mikeyhoward1977 in #178: @rikkilake I'm not sure how useful an employee notification would be only the first time an entry is added.\r\n\r\nSay the event is a wedding booked 12 months out and the bride/groom start adding songs to the playlist as soon as the event is confirmed. Employee would likely have no recollection of receiving the email by the time the event comes around.\r\n\r\nMore useful to have a task that auto sends the playlist to the employee once the playlist closes"}],"action":{"name":"View Issue","url":"https://github.com/mdjm/mobile-dj-manager/issues/178#issuecomment-313652255"}}}
