### ISSUE TITLE
Incorrect Duration in Client Zone for Event Start -End Times

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#229]
I have just changed my theme and started using the supplied template rather than the custom ones I have been using. While testing I found that my event scheduled for  90 minutes (1pm-2:30pm & 1:30pm-3pm) are showing a duration of 2hrs. See Below:

![capture-duration](https://user-images.githubusercontent.com/19335843/48979861-dc7cf880-f08e-11e8-80f5-d5b9efd00af3.JPG)

**Comment by deckbooks** [comment]
Thank you for reporting this bug we have confirmed that this is because we currently use the WordPress friendly time functions which round up to the nearest hour. In your example this should display as 1.5 hours but it is rounded to 2 hours.

We are in the process are moving away from the in-built WordPress function to our own which should be more accurate.
