### ISSUE TITLE
Enhancment - Communication Emails

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#78]
1. When an email fails to send, due to the subject line not being filled out for example, could the typed email not be blanked out so that the subject can be added without requiring the retyping of the whole email.
2. The spell checker points out miss spellings but it would be nice if the suggested spellings of the word are shown (could just be a FireFox issue I have not checked other browsers).

**Comment by mikeyhoward1977** [comment]
1. I can add a simply pop up stating the subject is empty rather than reloading the page to stop content being removed.
2. This is not MDJM or WordPress. I believe your browser is highlighting words it believes are not correctly spelled and placing a line under them.

As these aren't bugs I'm closing the comment. The alert will be added in an upcoming release - opened #79
