### ISSUE TITLE
On Update Venue Details button shows " -Select Venue-" and not the selected or entered Venue

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#96]
Because there is no indication that a venue has been selected unless a saved Venue was selected (Client Address and  Manual Entry show the -Select Address- button) I am not sure if I need to re-enter the venue information. This is probably what has led to some of the strange calendar entries I have been seeing, along with manual entries that were not saved as a venue, but did not get updated when the event was updated.

If I have selected to use the clients address I would expect the Venue details to show this and offer me an opportunity to change it and give the choice to select a new Venue, select the clients address, or add a new venue manually.

When  manually adding a Venue address for an event I would like to be able to use the venue for that event only (ie not save it as a Venue) and have the option to save the venue to the Venue list for use with other events, as with the older version. Saved venues should be for places that could be used by multiple clients and not cluttered with venues that are strictly limited to a client e.g. parents or friends homes.

**Comment by mikeyhoward1977** [comment]
The issue here is pretty simple... The value of the select field is not being recalled correctly when an existing event is in edit mode if the venue is set to Manual or Client Address.

The actual venue settings are saved and all associated content tags will function as expected.

Until resolution, drop the select list to "Manual" and the venue details will be displayed
