### ISSUE TITLE
Changing and recording a deposit on events page.

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#97]
Hi,

If I change the booking fee from a previously saved value of £40 to £30 on a event, click the Booking Fee paid checkbox and then Update the Event when the page reloads it saves the transaction as the old value of 40.

**Comment by rikkilake** [comment]
In other words someone hands you a lower booking fee than requested in cash but you still take it anyway.

**Comment by mikeyhoward1977** [comment]
Update the booking fee, save the event, then click booking fee paid will resolve this for now.

The reason is that the payment status checks are currently before the cost update in the process - I will look to change.

I personally would not reduce the Booking Fee amount if you receive a lower amount. Surely the booking fee remains the initial value (per contract) and the £30 is just a part payment towards? In which case you simply add an event transaction to the value of £30. Then when you either add another event transaction for £10 or over, the booking fee would be marked as paid. Like wise if you click the Booking Fee paid checkbox, a transaction would be entered for £10. Just my 2 cents :)
